# Generated by Django 2.0.7 on 2018-07-16 15:38

from django.db import migrations, models
import tools.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_blockproducer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creator_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tools.models.tool_logo_directory_path)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=True)),
                ('associated_bps', models.ManyToManyField(to='accounts.BlockProducer')),
                ('categories', models.ManyToManyField(to='tools.Category')),
            ],
        ),
    ]
