# Generated by Django 2.0.7 on 2018-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='tools.Category'),
        ),
    ]
