# Generated by Django 2.0.7 on 2018-07-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20180721_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='is_live',
        ),
        migrations.AddField(
            model_name='tool',
            name='status',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('PENDING', 'PENDING'), ('UNDER_DEV', 'UNDER_DEV')], max_length=20, null=True),
        ),
    ]
