# Generated by Django 2.0.7 on 2018-07-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20180721_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='associated_bps',
            field=models.ManyToManyField(blank=True, to='accounts.BlockProducer'),
        ),
    ]
