# Generated by Django 2.0.7 on 2018-07-30 17:41

from django.db import migrations, models
import tools.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20180726_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('creator_name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=tools.models.suggested_tool_logo_directory_path)),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LIVE', 'LIVE'), ('PENDING', 'PENDING'), ('UNDER_DEV', 'UNDER_DEV')], max_length=20, null=True)),
            ],
        ),
    ]
