# Generated by Django 2.0.7 on 2018-07-11 13:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='blockproducer',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='blockproducer',
            name='long',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='blockproducer',
            name='public_endpoint',
            field=models.URLField(null=True),
        ),
    ]
