# Generated by Django 2.0.7 on 2018-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180711_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockproducer',
            name='account_name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
