# Generated by Django 2.0.7 on 2018-07-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('faq', '0001_initial'),
        ('accounts', '0004_auto_20180711_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockproducer',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='BlockProducer',
        ),
    ]
