# Generated by Django 2.0.7 on 2018-07-11 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180711_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=12, unique=True)),
                ('producer_key', models.CharField(max_length=60)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('public_endpoint', models.URLField(null=True)),
                ('location', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
    ]
