# Generated by Django 2.0.7 on 2018-07-12 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blockproducer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProducerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.PositiveIntegerField()),
                ('block_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_position', to='accounts.BlockProducer')),
            ],
        ),
    ]
