# Generated by Django 2.0.7 on 2018-07-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_blockproducerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducerdata',
            name='votes',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=1000),
        ),
    ]
