# Generated by Django 2.0.7 on 2018-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blockproducerdata_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockproducerdata',
            name='votes',
        ),
        migrations.AddField(
            model_name='blockproducerdata',
            name='unweighted_votes',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='blockproducerdata',
            name='weighted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
