# Generated by Django 2.0.7 on 2018-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180712_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
