# Generated by Django 2.0.7 on 2018-07-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockproducer',
            old_name='long',
            new_name='lon',
        ),
    ]
