# Generated by Django 2.0.7 on 2018-07-13 13:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180713_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
