# Generated by Django 2.0.7 on 2018-07-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180713_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockproducer',
            name='location',
        ),
    ]
