# Generated by Django 2.0.7 on 2018-07-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_blockproducer_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockproducer',
            old_name='point',
            new_name='geom',
        ),
    ]
